# Generated by Django 4.1 on 2022-12-13 12:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='circular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('desc', ckeditor.fields.RichTextField()),
                ('photo', models.FileField(default='', upload_to='media/media/static')),
                ('date', models.CharField(default='', max_length=255)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='examapp.category')),
            ],
        ),
        migrations.DeleteModel(
            name='courses',
        ),
    ]
