# Generated by Django 4.1.4 on 2022-12-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_circular_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_for',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('fathername', models.CharField(default='', max_length=500)),
                ('cnic', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=1000)),
                ('hsc_board', models.CharField(default='', max_length=500)),
                ('hsc_percentage', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=100)),
                ('domicile', models.CharField(default='', max_length=300)),
                ('is_questian', models.BooleanField(default=True)),
                ('department', models.CharField(default='', max_length=300)),
                ('cnic_front', models.ImageField(default='', upload_to='media/media/static/')),
                ('cnic_back', models.ImageField(default='', upload_to='media/media/static/')),
                ('Applied_For', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examapp.apply_for')),
            ],
        ),
    ]
