# Generated by Django 4.1.4 on 2022-12-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0003_apply_for_registeration'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('desc', models.TextField()),
                ('files', models.FileField(upload_to='media/media/files/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
