# Generated by Django 4.1.4 on 2022-12-21 10:36

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0005_alter_downloads_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='examination_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('desc', froala_editor.fields.FroalaField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='downloads',
            name='desc',
            field=models.TextField(),
        ),
    ]
